version: "3.8"

services:
  co-github-analyzer:
    build: .
    container_name: github-analyzer
    ports:
      - 3000:3000
    working_dir: $PWD
    volumes:
      - $PWD:$PWD # this allows to share ./output/
    environment:
      GH_SECURITY_AUDITOR_TOKEN: ${GH_SECURITY_AUDITOR_TOKEN:-}
      GH_SECURITY_AUDITOR_USERNAME: ${GH_SECURITY_AUDITOR_USERNAME:-}
      GH_SECURITY_AUDITOR_PASSWORD: ${GH_SECURITY_AUDITOR_PASSWORD:-}
      GH_SECURITY_AUDITOR_OTP_SEED: ${GH_SECURITY_AUDITOR_OTP_SEED:-}
