name: release

permissions:
  contents: write

on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Fetch git tags
        run: git fetch --force --tags

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.2"
          cache: true

      - uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ github.token }}
